man-group/arctic

arctic/store/version_store.py, tests/integration/store/test_version_store.py, tests/unit/store/test_version_store.py
Added versions parameter to snapshot specific versions of symbols in version store.
=> Snapshot specific symbol versions

arctic/arctic.py, tests/unit/test_arctic.py
authenticated when the library binding is created
=> MDP-341 Reauthing as admin if connection is not

CHANGES.md, README.md, arctic/store/_ndarray_store.py, arctic/store/_pandas_ndarray_store.py, arctic/store/version_store.py, tests/integration/store/test_pandas_store.py, tests/unit/store/test_version_store.py
Add initial support for querying Pandas DataFrames with a DateRange slice (reducing the number of documents read).
=> Pandas DateRange query support

arctic/store/_base_store.py, arctic/store/_ndarray_store.py, arctic/store/_pandas_ndarray_store.py, arctic/store/_pickle_store.py, arctic/store/audit.py, arctic/store/version_store.py, arctic/store/versioned_item.py, tests/integration/store/test_ndarray_store.py, tests/integration/store/test_pandas_store.py, tests/integration/store/test_pickle_store.py, tests/unit/store/test_version_item.py, tests/unit/store/test_version_store_audit.py
=> Expose data info via read_metadata

CHANGES.md, MANIFEST.in, setup.py
Removed MANIFEST file and use setuptools-git instead, its more fool-proof to include all the header and source files. Updated changelog.
=> Use setuptools-git

arctic/store/_pandas_ndarray_store.py, tests/unit/store/test_pandas_ndarray_store.py
=> Should check tz metadata for None for backward compatibility. Fixes #81

tests/unit/date/test_mktz.py, tests/unit/date/test_util.py, tests/unit/store/test_version_item.py, tests/unit/store/test_version_store_audit.py, tests/unit/test_compression.py, tests/unit/test_fixtures.py, tests/unit/test_multi_index.py, tests/unit/test_util.py, tests/unit/tickstore/test_toplevel.py
Addresses gaps in code coverage
=> new unit tests

arctic/date/_parse.py, tests/integration/tickstore/test_ts_read.py, tests/unit/date/test_daterange.py
Take a look @jamesblackburn 
this resolves issues #118 and #119
=> Fixes to support latest versions of dateutil and Numpy

.coveragerc, arctic/arctic.py, arctic/chunkstore/_chunker.py, arctic/chunkstore/chunkstore.py, arctic/chunkstore/date_chunker.py, arctic/decorators.py, arctic/fixtures/arctic.py, arctic/serialization/pandas_serializer.py, arctic/store/_ndarray_store.py, arctic/store/_pandas_ndarray_store.py, arctic/store/_pickle_store.py, arctic/store/version_store.py, tests/integration/chunkstore/test_chunkstore.py, tests/integration/store/test_ndarray_store.py, tests/unit/serialization/test_serializer.py, tests/unit/store/test_pandas_ndarray_store.py
New storage type that supports custom chunkers
- supports write/read/append/update
- new chunker type, DateChunker, chunks by Day, Month, Year
=> Chunk store

README.md
make the demo work with current quandl
=> quandl changes

CHANGES.md, arctic/chunkstore/chunkstore.py
see issue #166 for complete details.
=> Chunkstore SHA Index

CHANGES.md, arctic/chunkstore/chunkstore.py, tests/integration/chunkstore/test_chunkstore.py
Check that dtypes match in old chunks vs new chunks.
=> Fix for issue #169

CHANGES.md, arctic/chunkstore/_chunker.py, arctic/chunkstore/chunkstore.py, arctic/chunkstore/date_chunker.py, tests/integration/chunkstore/test_chunkstore.py, tests/unit/chunkstore/test_date_chunker.py
See issues #171 and #172  for more information.
=> Fixes #171 and #172

CHANGES.md, arctic/chunkstore/chunkstore.py, tests/integration/chunkstore/test_chunkstore.py
=> Fix issue #176

CHANGES.md, arctic/chunkstore/chunkstore.py, tests/integration/chunkstore/test_chunkstore.py
See #162 - Adds a rename method to ChunkStore to allow symbol renaming.
=> Feature #162

CHANGES.md, arctic/chunkstore/chunkstore.py, tests/integration/chunkstore/test_chunkstore.py
- Allow user to update with a chunk_range
- Fix issue #189 which causes rows and chunk counts to be incorrect after a range delete
=> Feature #186 and Bugfix #189

tests/unit/date/test_datetime_to_ms_roundtrip.py
Works now with latest changes to timezone handling - see #159
=> Remove xfailed test

arctic/tickstore/toplevel.py, tests/integration/tickstore/test_toplevel.py, tests/unit/tickstore/test_toplevel.py
Date ranges for top level libraries are stored as timezone naive datetimes. These are now converted into UTC before using these dates to split up the tick data into slices to writing to the low level tickstore libraries. We also fix an xfailed test and add an extra check that data written to in one timezone can be fetched out in another.
=> Tickstore top level write fix

arctic/chunkstore/chunkstore.py, arctic/chunkstore/date_chunker.py, tests/integration/chunkstore/test_chunkstore.py, tests/unit/chunkstore/test_date_chunker.py
=> Date Chunker support for DatetimeIndexes

arctic/chunkstore/chunkstore.py, tests/integration/chunkstore/test_chunkstore.py
=> Upsert capability for update in ChunkStore

arctic/arctic.py, tests/integration/test_arctic.py
=> Add rename support for Libraries in Arctic

arctic/store/_pickle_store.py, tests/integration/store/test_pickle_store.py, tests/unit/store/test_pickle_store.py
Fixes #219 and #220
@TomTaylorLondon @vmereuta @Wilfred
=> Fix issues #219 and #220

arctic/chunkstore/_chunker.py, arctic/chunkstore/chunkstore.py, arctic/chunkstore/date_chunker.py, arctic/chunkstore/passthrough_chunker.py, arctic/serialization/_serializer.py, arctic/serialization/numpy_arrays.py, arctic/serialization/numpy_records.py, tests/integration/chunkstore/test_chunkstore.py, tests/unit/chunkstore/test_date_chunker.py, tests/unit/chunkstore/test_passthrough_chunker.py, tests/unit/serialization/test_numpy_arrays.py
Addresses issue #193  and issue #212 
Also #222 
take a look @jamesblackburn and @miketkelly
=> Support for different chunkers/serializers by symbol

src/_compress.pyx, tests/integration/test_compress_integration.py
=> Fix for decompression issue

arctic/chunkstore/chunkstore.py, arctic/date/_daterange.py, tests/integration/chunkstore/test_chunkstore.py
=> Features: get_chunk_range + iterator access on ChunkStore

arctic/chunkstore/chunkstore.py, tests/integration/chunkstore/test_chunkstore.py
=> Improve chunkstores get_info output

arctic/arctic.py, tests/integration/test_arctic.py
=> Add support for get_library_type in Arctic

CHANGES.md, arctic/chunkstore/date_chunker.py, tests/integration/chunkstore/test_chunkstore.py, tests/unit/chunkstore/test_date_chunker.py
=> Chunkstore open range read

arctic/chunkstore/chunkstore.py, arctic/serialization/numpy_arrays.py, setup.py, tests/integration/chunkstore/test_chunkstore.py
=> Add quota to chunkstore and fix writes with missing column names

arctic/tickstore/tickstore.py, tests/integration/tickstore/test_ts_delete.py
I want to know if anything is deleted, since the `delete` action will only delete fully contained in the passed in date_range.
=> TickStore.delete: Return result of deletion

arctic/chunkstore/chunkstore.py, arctic/chunkstore/date_chunker.py, arctic/chunkstore/passthrough_chunker.py, arctic/serialization/numpy_arrays.py, tests/unit/chunkstore/test_passthrough_chunker.py
nothing critical, or even that important, except I'm tired of seeing the warnings for these in the IDE :)
=> Pylint fixes

arctic/serialization/numpy_arrays.py, tests/unit/serialization/test_numpy_arrays.py
=> refactor deserialize and add in check for duplicate columns

CHANGES.md, arctic/chunkstore/date_chunker.py, tests/unit/chunkstore/test_date_chunker.py
=> Fix issue #275

.github/ISSUE_TEMPLATE.md
=> Issues template

.travis.yml
- more modern linux distro
- newer version of mongo
This seems to fix the incessant mongo connection errors that have been plaguing the builds. 
=> Update Travis Build Parameters

CHANGES.md, arctic/chunkstore/date_chunker.py, tests/integration/chunkstore/test_chunkstore.py, tests/unit/chunkstore/test_date_chunker.py
=> Fix issue #283

CHANGES.md, arctic/chunkstore/chunkstore.py, arctic/store/version_store.py, tests/integration/chunkstore/test_chunkstore.py
=> support for has_symbol and updates to list_symbols

CHANGES.md, arctic/_util.py, arctic/store/version_store.py, tests/integration/scripts/test_enable_sharding.py
- hashed based sharding by default
- be less specific about the database already sharded exception from
mongo
=> Tweak the enable_sharding command

CHANGES.md, arctic/chunkstore/chunkstore.py, tests/integration/chunkstore/test_chunkstore.py
Set and read user defined per-symbol metadata
=> Issue #313 User Defined Metadata

CHANGES.md, arctic/tickstore/tickstore.py, tests/integration/tickstore/test_ts_write.py
Fixes issues #216. This issue already addressed by PR #217, but author has not responded to requests for unit tests, so I've added one to this PR
=> Fix issue 216

README.md
=> Added GitHub link

arctic/arctic.py, arctic/chunkstore/chunkstore.py, arctic/store/version_store.py, arctic/tickstore/tickstore.py, arctic/tickstore/toplevel.py, tests/integration/test_arctic.py, tests/unit/test_arctic.py
We'd like to provide a way to clean up the underlying MongoClient.
=> Add reset() method to Arctic

arctic/arctic.py, tests/integration/test_arctic.py
To avoid deadlock when calling reset()
=> Make Arctic._lock reentrant

arctic/chunkstore/chunkstore.py, tests/integration/chunkstore/test_chunkstore.py
=> Fix bug in chunkstore

arctic/store/_pandas_ndarray_store.py, tests/integration/store/test_version_store.py
fixes issue #346 
@TomTaylorLondon let me know what you think. Would still like to have an example dataframe for a unit test :)
=> Fix issue #346

.travis.yml, setup.py
=> Temporary workaround for pandas deprecation

.travis.yml, setup.py
=> Revert "Revert lz4 pinning"

CHANGES.md, arctic/store/version_store.py, tests/integration/store/test_version_store.py
On empty appends the data returned has the incorrect version, this fixes that issue
=> Fix issue #360

arctic/arctic.py, arctic/store/bson_store.py, tests/unit/store/test_bson_store.py
As discussed before, this is a generic BSON store for Arctic, which is really just exposing the underlying pymongo functionality within the framework of Arctic.
=> Add generic BSON store to Arctic

arctic/store/bson_store.py, tests/unit/store/test_bson_store.py
I'd like to use a few more calls for the project I'm currently working on. I've also aligned the names of arguments with the pymongo API for better consistency.
=> Expose more calls in the BSONStore

arctic/arctic.py, arctic/fixtures/arctic.py, arctic/store/bson_store.py, arctic/store/metadata_store.py, tests/integration/store/test_metadata_store.py, tests/unit/store/test_bson_store.py, tests/unit/store/test_metadata_store.py
This stores metadata with timestamps to allow temporal queries.
This is migrated from PR390.
=> MetadataStore

CHANGES.md, arctic/chunkstore/chunkstore.py, tests/integration/chunkstore/test_chunkstore.py
@jamesblackburn @RichardWarfield please take a look. This addresses #394 
Its likely it doesnt 100% work correctly yet - I just wanted to code up a proof of concept and a simple unit test to test out base functionality. I haven't updated doc strings, or written up more complicated test cases with things like date ranges, symbols that do not exist, symbols outside of a date range, etc. 
I will add those tests and update the documentation assuming that this is in the right direction.
I also have not updated / changed tickstore or version store. I assume this is something we'd want in VersionStore but not Tickstore. Let me know @jamesblackburn
=> Multi Symbol Read for ChunkStore

arctic/chunkstore/chunkstore.py, tests/integration/chunkstore/test_fixes.py
=> Iterators not accounting for multiple segments in chunkstore

arctic/chunkstore/chunkstore.py, tests/integration/chunkstore/test_chunkstore.py, tests/integration/chunkstore/test_fixes.py
=> fix error when delete range produces an empty df

CHANGES.md, arctic/tickstore/tickstore.py, tests/integration/tickstore/test_ts_read.py
=> User defined metadata for tickstore

setup.py
Clang 5.0 (easily installed with homebrew) seamlessly supports openMP
=> support for clang 5.0 on OSX

tests/integration/test_arctic_multithreading.py
Didn't want to use Mocks in an integration test, used an actual auth hook
=> integration test for auth fix with multiprocessing

arctic/tickstore/tickstore.py, tests/integration/tickstore/test_toplevel.py
Add min date function to match max date function
=> ENH: Add min date function

arctic/_util.py, arctic/chunkstore/chunkstore.py, arctic/chunkstore/tools/tools.py, arctic/fixtures/arctic.py, arctic/hosts.py, arctic/multi_index.py, arctic/scripts/arctic_create_user.py, arctic/store/_ndarray_store.py, arctic/store/bson_store.py, arctic/store/version_store.py, benchmarks/benchmarks.py, howtos/201507_demo_pydata.py, tests/integration/chunkstore/test_chunkstore.py, tests/integration/chunkstore/test_fixes.py, tests/integration/scripts/test_list_libraries.py, tests/integration/store/test_ndarray_store_append.py, tests/integration/tickstore/test_ts_delete.py, tests/unit/store/test_pickle_store.py
Remove unused imports, trailing whitespace, fix overridden built in functions, etc
=> Code cleanup

CHANGES.md, arctic/store/version_store.py, setup.py, tests/unit/store/test_version_store.py
=> Make retry logic more robust to failures for version store write/append

CHANGES.md, arctic/serialization/numpy_arrays.py, arctic/store/_ndarray_store.py, arctic/store/_pandas_ndarray_store.py, arctic/tickstore/tickstore.py, tests/integration/store/test_ndarray_store.py, tests/integration/store/test_pandas_store.py, tests/integration/test_arctic_multithreading.py
=> Revert to using back fromstring instead of frombuffer

arctic/chunkstore/chunkstore.py
Speed up check invalid segments check.
=> speed up _check_invalid_segment warning

CHANGES.md, arctic/chunkstore/chunkstore.py
Required so the check isn't a heavy operation once the segments have been upgraded.
=> adding segment index

CHANGES.md, arctic/arctic.py, tests/unit/test_arctic.py
Adding param to disable check.
=> Increasing number of libraries to 5000

CHANGES.md, arctic/store/version_store.py, tests/integration/store/test_version_store.py, tests/unit/store/test_version_store.py
=> Issue #508 - List symbols returning deleted symbols

arctic/arctic.py
Fixes issue #271:
Adds logging functionality when the library does not exist.
=> Delete lib log missing

setup.py
=> Use latest pytest

CHANGES.md, arctic/arctic.py, arctic/store/_ndarray_store.py, arctic/store/_version_store_utils.py, arctic/store/version_store.py, setup.py, tests/integration/store/test_version_store.py, tests/integration/store/test_version_store_corruption.py, tests/unit/store/test_version_store.py
This will just merge the hotfix release branch changes onto master.
The hotfix release was branched from 1.67.0 , not from master HEAD, hence required rebasing the hotfix branch on master + conflict resolution before we can merge.
=> Release restore hotfix merge on master

arctic/tickstore/tickstore.py, tests/integration/tickstore/test_ts_read.py
=> fix tickstore unicode handling, support both unicode and utf-8 arrays.

arctic/chunkstore/chunkstore.py
=> fix issue 594 - enable sharding for chunkstore

CHANGES.md, arctic/_compression.py
Rather than create a ThreadPool as soon arctic is imported, create it when its first used by Arctic
see issue #612
=> resolve issue 612

CHANGES.md, arctic/chunkstore/chunkstore.py, docs/chunkstore.md, tests/integration/chunkstore/test_chunkstore.py
Add upsert to append in chunkstore. Default is false, so it wont break anything and is backwards compatible.
=> Add upsert to Append in ChunkStore

CHANGES.md, README.md, arctic/serialization/numpy_arrays.py, tests/integration/chunkstore/test_chunkstore.py
=> Columns fix

CHANGES.md, arctic/serialization/numpy_records.py, tests/integration/store/test_version_store.py, tests/unit/serialization/test_numpy_records.py
Fixes issue: #157 
We have breakages due to this issue, this is a high priority fix.
=> Fix for handling the dtype conversion of object to string safely

CHANGES.md, arctic/store/_pandas_ndarray_store.py, tests/integration/store/test_version_store.py, tests/unit/serialization/serialization_test_data.py
=> Fixed issue with write errors, non-detecting objects in multi-index

arctic/__init__.py
=> Add version to arctic module

setup.py
=> replace enum34 requirement with enum-compat

arctic/store/_pandas_ndarray_store.py
=> Check if panel has index first

arctic/arctic.py, tests/integration/test_arctic.py, tests/unit/test_arctic.py
=> Add library_exists implementation

arctic/_compression.py, arctic/_config.py, arctic/_util.py, arctic/date/_mktz.py, arctic/decorators.py, arctic/serialization/incremental.py, arctic/serialization/numpy_records.py, arctic/store/_ndarray_store.py, arctic/store/_version_store_utils.py, arctic/store/version_store.py, benchmarks/fast_serializable_check.py, tests/integration/store/test_ndarray_store.py, tests/integration/store/test_version_store.py, tests/integration/store/test_version_store_corruption.py, tests/unit/serialization/test_numpy_records.py, tests/unit/serialization/test_pandas_is_serializable.py, tests/unit/store/test_version_store.py
Implements feature #665  
@yschimke  @jamesblackburn @bmoscon
=> moving all env variable configuration driven variables in arctic._config

docs/README.md, docs/configuration.md
=> Add config docs

README.md, docs/chunkstore_api.md, docs/quickstart.md, docs/releasing.md, docs/users.md, mkdocs.yml
Adds more documentation updates as part of https://github.com/manahl/arctic/issues/681
=> More documentation changes

benchmarks/benchmarks.py
it should be [n] * x instead of [n * x], this was breaking
asv run for me.
https://github.com/manahl/arctic/issues/694
=> 694: Fix Benchmarks

arctic/store/bson_store.py
This reverts commit b42130a9168537ae2f5cf6eb10dc5df035525cd3.
As tests expect this argument to be present in all stores.
=> Revert "Drop hashing=True in initialize bsonstore"

benchmarks/fwd_pointers/fwd_benchmarks.py
This can be improved and cleaned up quite a bit, but want to commit
at a checkpoint rather than doing everything locally.
=> Add basic benchmarks for forward pointers

CHANGES.md, arctic/serialization/numpy_arrays.py
=> Fix issue #712 - pandas deprecation warning in chunkstore serializer

arctic/fixtures/arctic.py, arctic/store/version_store.py, tests/integration/store/test_version_store.py, tests/unit/store/test_version_store.py
Based on discussions and given the fact that this collection is
not exposed via any api, it should be safe to remove all usage
of this.
=> Fixes #714 Do not write to changes collection

CHANGES.md
Add all the changes since the last release (1.73)
=> Update changes.md with all new changes

arctic/_cache.py, arctic/serialization/numpy_arrays.py, tests/integration/chunkstore/test_fixes.py
fix #722 as well as several deprecation warnings in other parts of the code
=> Fix issue 722 and deprecation warnings

arctic/chunkstore/chunkstore.py, arctic/serialization/numpy_arrays.py, setup.py, tests/integration/chunkstore/test_fixes.py
* Improve column list copy + add test
* fix exception when empty symbol has get_info called on it
=> Chunkstore Improvements + fixes

arctic/store/_ndarray_store.py
Adds an error message with details when this happens.
=> Fixes 753: Add details to bulk write failures

CHANGES.md, setup.py
Updating arctic to the next version. Will push to pypi with twine next.
=> Roll forward setup.py to 1.76 and update CHANGES.md with fixes

CHANGES.md, setup.py
Updated these before putting out the release. Changing it back. Will update after the release
=> Add changes.md date and setup.py after push to pypi

arctic/_config.py, arctic/store/_pandas_ndarray_store.py
This allows people to have this behaviour without having to change
the client code.
=> Allow setting force_bytes_to_unicode from env

CHANGES.md, setup.py
The next one will be 1.77 because I messed up 1.75 and 1.76 🙈
=> Change next arctic release number

CHANGES.md, setup.py
=> Release 1.78 and tick over the next version to 1.79

arctic/serialization/numpy_records.py, tests/integration/store/test_pandas_store.py
When read back with py3, the str accessor for pandas 0.22.0 does not
work for indexes if all data is bytes type. I added a test for py3
reading as well, and astype works for all these cases.
=> Use astype vs using str accessor to convert to unicode

CHANGES.md, setup.py
Tick over setup.py and close 1.79.0 bug list
=> Release 1 79

CHANGES.md, arctic/serialization/numpy_records.py, docs/releasing.md, setup.py, tests/integration/store/test_pandas_store.py
+ add a test + new version info
=> Handle multi indexes when converting to unicode

arctic/_cache.py, arctic/_config.py, arctic/arctic.py
This could be useful for globally disabling something in tests by
setting it in the env.
=> Add back env variable for disabling cache

arctic/_cache.py
This log can be quite spammy as people generally do not not have listCollections on this db.
=> Convert log to debug

arctic/store/version_store.py
As part of https://github.com/manahl/arctic/issues/789 this allows this param to be passed along to prune_previous_versions
=> Allow passing keep_mins in write and append

arctic/serialization/numpy_records.py, arctic/store/_pandas_ndarray_store.py, tests/integration/store/test_pandas_store.py
This is a proposed fix for #831
=> Support FORCE_BYTES_TO_UNICODE with pd.Series (#831)

arctic/store/_version_store_utils.py, arctic/tickstore/toplevel.py
The build is failing due to some flake8 issues:
```
$ pycodestyle arctic
arctic/tickstore/toplevel.py:101:66: E741 ambiguous variable name 'l'
arctic/tickstore/toplevel.py:108:13: E741 ambiguous variable name 'l'
arctic/tickstore/toplevel.py:142:79: E741 ambiguous variable name 'l'
arctic/store/_version_store_utils.py:149:20: E741 ambiguous variable name 'l'
arctic/store/_version_store_utils.py:296:23: E741 ambiguous variable name 'l'
arctic/store/_version_store_utils.py:321:23: E741 ambiguous variable name 'l'
arctic/store/_version_store_utils.py:344:18: E741 ambiguous variable name 'l'
The command "pycodestyle arctic" exited with 1.
```
This PR fixes these issues
=> Fix flake8 errors

.circleci/config.yml
=> remove large docker build resource

arctic/chunkstore/chunkstore.py
Parameter should be "partial_match", not "partial".
=> Fix doc for chunkstore's list_symbols
