README.md
arctic/_compression.py
tests/integration/store/test_pickle_store.py
tests/unit/date/test_datetime_to_ms_roundtrip.py
tests/unit/date/test_mktz.py
tests/unit/date/test_util.py
tests/unit/store/test_version_store.py

- Fix the tests that assume local == London
- Fix deprecation warning in newer bumpy
Fixes #2

Circleci build and cov

---

arctic/arctic.py
tests/unit/test_arctic.py

It previously dropped app_name and the various timeout params.

Ensure Arctic.__getstate__ persists all init params.

---

arctic/store/version_store.py
tests/unit/store/test_version_store.py

When deleting a symbol we assert it's really gone using has_symbol(). This assertion can fail when reading from a secondary cluster member.
This change adds the allow_secondary argument to the has_symbol() method, and a little refactoring of the code to determine the mongo read preference.

Delete assertion must read from master

---

arctic/decorators.py
tests/unit/test_decorators_unit.py

Call the hook via hooks.py rather than importing it into decorators.

MDP-341 ensure the external error hook is called when an exception occurs

---

arctic/date/_util.py
arctic/store/_pandas_ndarray_store.py
tests/integration/store/test_pandas_store.py

- Fix index out of bounds error when reading beyond the end of a chunk
- We don't current support TimeZones for DateRange slicing

Bugfix/mdp 568 pandas date-range read issues in arctic

---

CHANGES.md
arctic/store/_pandas_ndarray_store.py

From Tom: Saving a 3GB multi-index Pandas DF takes >10 minutes:
```
from pandas import DataFrame, date_range
from datetime import datetime as dt
from itertools import product
import numpy as np
from pandas.tools.util import cartesian_product
dates = date_range(dt(2000, 1, 1), dt(2015, 1, 1))
ids = range(6000)
idx = cartesian_product((dates, ids))
df = DataFrame(index=idx)
for c in range(12):
df['c_%s' % c] = np.random.randn(len(df))
size = (df.values.nbytes + df.index.nbytes + df.columns.nbytes) / 1e6
print size
from arctic import Arctic
from datetime import datetime as dt
m = Arctic('research')['tptaylor.alphas']
now = dt.now()
m.write('xx', df)
print dt.now() – now
```

Speedup saving of Pandas Series/Dataframes with MultiIndex containing a date

---

CHANGES.md
arctic/auth.py
tests/unit/test_auth.py

Other derivatives of PyMongoError indicate other issues, so rather than
silently hide them, we should propagate them to the caller.

MDP-574 Only catch OperationFailure exceptions during auth

---

arctic/store/version_store.py
tests/integration/store/test_version_store.py
tests/unit/store/test_version_store.py

This way we can check whether or not the leading version is just a sentinel put in by version_store.delete().

EASY-511 return deleted state in list_versions

---

CHANGES.md
arctic/store/_ndarray_store.py
arctic/store/_pandas_ndarray_store.py
arctic/store/_pickle_store.py
arctic/store/version_store.py
tests/integration/store/test_ndarray_store.py
tests/integration/store/test_pandas_store.py
tests/integration/store/test_pickle_store.py

allows user to get information about stored data without reading back the whole df/series/etc
see: NI-370

new VersionStore API - get_data_info

---

arctic/store/_ndarray_store.py
arctic/store/_pandas_ndarray_store.py
tests/unit/store/test_pandas_ndarray_store.py

This addresses issue #37 
In new versions of NumPy there is an issue ( see https://github.com/numpy/numpy/issues/6771 ) that causes the dtype metadata to be lost. Additionally, the actual dtype has changed when using NumPy records as well. This pull request addresses these issues and works with the current supported versions of NumPy and Pandas (1.9.2 and 0.16.2) as well as the latest versions (1.10.1 and 0.17.1)

Fix issue with new versions of NumPy that cause dtype metadata to be lost

---

arctic/store/audit.py
tests/unit/store/test_version_store_audit.py

This is useful for batch jobs that require 'transactional' access to
VersionStore (i.e. read-modify-write without intervening update), but
don't necessarily want to keep all versions in perpetuity.

Add support non-audited transactions.

---

arctic/store/_pandas_ndarray_store.py
tests/integration/store/test_bitemporal_store.py
tests/integration/store/test_pandas_store.py

If a multi-index dataframe with timezone info in index is written into pandas store, the info shoulnd't be lost on read. Fix #59.

Multiindex timezone support

---

arctic/tickstore/tickstore.py
tests/integration/test_arctic.py

Try to fix https://github.com/manahl/arctic/issues/49

Add import indent

---

tests/integration/tickstore/test_toplevel.py

The integration tests in integration/tickstore/test_toplevel.py are not prefixed with test. Py.test will not run any of these tests. 
I added "test_" to the tests and fixed a few errors in the code. Some tests still will not pass (either because of a bug in the test or in the code), so these have been marked xfail. Whoever wrote them should go back and take a look at the broken tests. (I'll open a ticket for them once this gets merged in).

Unit tests need to be prefixed with test_

---

.travis.yml
README.md
setup.py

A few other changes now that Python 3.4 is supported (thanks to the changes that allow us to support Mock 1.3.0)

Python 3.4 Support

---

arctic/tickstore/toplevel.py
tests/integration/tickstore/test_toplevel.py

A read across two or more lower level tickstore libraries where one of them contained no data would raise a NoDataFoundException even though the others had returned data. This change fixes the bug and returns data.
@bmoscon @jamesblackburn

Top level read fix for #95

---

arctic/tickstore/tickstore.py
tests/integration/tickstore/test_ts_write.py

Adding tests to detect doc['e'] being set incorrectly. Changing code in tickstore.py to fix the bug.
It seems that assert_frame_equal occasionally raises in error, I don't think my changes have caused this.

Fix pandas write

---

arctic/tickstore/tickstore.py
tests/integration/tickstore/test_ts_delete.py
tests/integration/tickstore/test_ts_read.py
tests/integration/tickstore/test_ts_write.py
tests/unit/tickstore/test_tickstore.py

The tickstore code has supported initial images with each document for some time but the write() call could not write the data. This PR allows for an initial_image field. We also change the init to enable the chunk_size to be set on creation. A number of methods get changed to staticmethods.

Tickstore write initial images

---

CHANGES.md
arctic/store/_pandas_ndarray_store.py
tests/integration/store/test_pandas_store.py
tests/unit/store/test_pandas_ndarray_store.py

Ensure rows with nans are not dropped by passing ``filter_observations=False``
to ``panel.to_frame``.

Fix pd.Panel storage.

---

arctic/date/_mktz.py
arctic/store/bitemporal_store.py
arctic/tickstore/tickstore.py
tests/integration/store/test_bitemporal_store.py

We want to ensure that data with identical timestamp isn't unnecessarily
perturbed.  Merge sort provides a stable sort:
http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.sort_index.html#pandas.DataFrame.sort_index

Use mergesort for Index sorting.

---

arctic/tickstore/tickstore.py
tests/integration/tickstore/test_ts_read.py
tests/unit/tickstore/test_tickstore.py

I think this fixes #129 -- make sure we get earliest start of the (for each symbol) closest chunk to our start datetime.

Correct chunk start bounds calculation

---

.gitignore
arctic/store/version_store.py
tests/integration/store/test_version_store.py

Will throw an error if the symbol exists but has been deleted (by checking the 'deleted' metadata) - tests for this behavior already exist.
Will no longer throw an exception when reading a legitimate None from version store.

FSF-264 Allow reading of None values from arctic

---

arctic/exceptions.py
arctic/tickstore/tickstore.py
tests/integration/tickstore/test_ts_read.py
tests/unit/tickstore/test_tickstore.py

We now raise an arctic.exceptions.UnorderedDataException if data goes
backwards within one chunk.

MDP-934 Ensure that the time always goes forwards in a tickstore bucket

---

.travis.yml
CHANGES.md
arctic/tickstore/tickstore.py
tests/integration/tickstore/test_ts_read.py
tests/unit/tickstore/test_tickstore.py

Currently this flag is used by VersionStore to allow querying replicas
for scalability.  Although Mongo supports fairly complex server
selection, in Arctic we give the user a binary choice - PRIMARY
(allow_secondary=False) or NEAREST (allow_secondary=True)

TickStore should respect the allow_secondary flag on Arctic

---

CHANGES.md
arctic/arctic.py
tests/unit/test_arctic.py

Previously the quota was cached indefinitely, and if the quota was increased, the new quota wasn't being picked up until the application was restarted. Re-checking the quota after every countdown (half-life) now picks up any changes made to the library whilst the application is still running.

Re-cache the library quota periodically

---

src/_compress.pyx

pip install arctic complained about absent stdint.h on msvc
Used python 64 bit from MiniConda distribution.

windows msvc stdint.h absent compatibility

---

setup.py

There're somehow two `__init__.py` files inside `tests/` and `benchmarks/`, which will be included in the arctic dist package:
```
In [3]: find_packages()
Out[3]:
['arctic',
'benchmarks',
'tests',
'arctic.chunkstore',
'arctic.date',
'arctic.fixtures',
'arctic.scripts',
'arctic.serialization',
'arctic.store',
'arctic.tickstore',
'tests.integration',
'tests.unit',
'tests.integration.chunkstore',
'tests.integration.fixtures',
'tests.integration.scripts',
'tests.integration.store',
'tests.integration.tickstore',
'tests.unit.date',
'tests.unit.scripts',
'tests.unit.serialization',
'tests.unit.store',
'tests.unit.tickstore']
In [4]: find_packages(include=("arctic*", ))
Out[4]:
['arctic',
'arctic.chunkstore',
'arctic.date',
'arctic.fixtures',
'arctic.scripts',
'arctic.serialization', …
```

packaging: Exclude benchmarks and tests

---

CHANGES.md
arctic/chunkstore/_chunker.py
arctic/chunkstore/chunkstore.py
arctic/chunkstore/date_chunker.py
tests/integration/chunkstore/test_chunkstore.py

- Fix append
- Rework Append and Update to share code (since 99% of their code is identical)
- Change how start/end are stored in Mongo. Previously was the actual start/end of the data, now is start/end of the chunk size. This makes the code less complex.

Fix issue #178

---

arctic/date/_mktz.py
tests/integration/tickstore/test_ts_read.py
tests/unit/date/test_datetime_to_ms_roundtrip.py
tests/unit/date/test_mktz.py
tests/unit/date/test_util.py

- Use dateutil.tz.gettz rather than loading tzfiles directly - this
should support Windows:
https://labix.org/python-dateutil#head-b79630fbbda87af6d6d121737510fd7ea5aeea97
- Don't load the default timezone on module import (we shouldn't do
additional I/O here)
- Remove custom tzfile binary-search implementation, this was fixed
upstream in dateutil: 
https://github.com/dateutil/dateutil/commit/1205f3cea1452f54eee9792034e433afc0ecffc5 
Fixes #43

Remove timezone path dependency on *nix

---

arctic/tickstore/tickstore.py

```python
Traceback (most recent call last):
File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
self.run()
File "/vagrant/projects/x/x/scripts/x_import_market_data.py", line 143, in run
self.tick_library.write(instrument_id, [tick_dict])
File "/vagrant/projects/x/venv/local/lib/python2.7/site-packages/arctic-1.26.0-py2.7-linux-x86_64.egg/arctic/tickstore/tickstore.py", line 533, in write
self._write(buckets)
File "/vagrant/projects/x/venv/local/lib/python2.7/site-packages/arctic-1.26.0-py2.7-linux-x86_64.egg/arctic/tickstore/tickstore.py", line 540, in _write
logger.debug("%d buckets in %s: approx %s ticks/sec" % (len(buckets), t, int(ticks / t)))
ZeroDivisionError: float division by zero
```
This traceback looks strange but any it happened (just once in my …

TickStore: Fix ZeroDivisionError

---

.travis.yml
setup.py

Latest version of PyTest deprecates a call that pytest-dbfixtures makes, resulting in an error when running pytest. This forces setup.py and Travis to use the previous version of pytest

Pytest fix

---

CHANGES.md
arctic/store/version_store.py
tests/integration/store/test_version_store.py

It can be the case that the previous append fails (which is reported
back to the caller), and subsequent appends won't be allowed until a
read()+write() are called.  Log an error, but allow the new append to
proceed.
Fixes MDP-1054 / Issue #228

Don't raise during append(...) if the previous append didn't succeed.

---

tests/integration/store/test_version_store.py

We raise an OperationFailure exception when something goes wrong
querying the database as a secondary.  Arctic retries querying the
primary only, and we assert that data comes back.

Fix the test when run against new MongoDBs.

---

arctic/arctic.py
tests/unit/test_arctic.py

- Add Library names to the quota waring and info lines
- WARN when library >90% full 
Currently we only warn when we're within 100 (average sized chunks) f
being full.  In addition WARN when the library is >90% (the warning may
still be infrequent if we're many chunks away from filling the library).

Mongo quota improvements

---

CHANGES.md
arctic/store/version_store.py
tests/unit/store/test_version_store.py

ensure_index takes a database write lock, which may be very slow.  We
already create the indexes on library initialisation.
For example:
```
2016-10-18T09:57:15.891+0100 I COMMAND [conn2904064] command
mongoose_oneminute.$cmd command: createIndexes { createIndexes: "LIVE",
indexes: [ { unique: true, background: true, name: "symbol_1_sha_1",
key: { symbol: 1, sha: 1 } } ] } keyUpdates:0 writeConflicts:0
numYields:0 reslen:149 locks:{ Global: {
acquireCount: { r: 1, w: 1 } }, MMAPV1Journal: { acquireCount: { w: 2
}, acquireWaitCount: { w: 1 }, timeAcquiringMicros: { w: 235168 } },
Database: { acquireCount: { W: 1 }, acquireWaitCount: { W: 1 },
timeAcquiringMicros: { W: 836 } } } 236ms
2016-10-18T09:57:15.891+0100 I COMMAND [conn2904078] command
mongoose_oneminute.$cmd command: createIndexes …
```

MDP-1292 Don't ensure_index on every VersionStore.append() / write()

---

CHANGES.md
arctic/chunkstore/chunkstore.py
tests/integration/chunkstore/test_chunkstore.py

This change will help future proof the storage of metadata, and allow us to store per symbol user defined metadata (not implemented yet). Also prevents a vert large sized metadata from drastically reducing the chunking size of every part of a chunk for chunks over 16MB.

Move chunkstores per-chunk metadata to its own collection

---

CHANGES.md
src/_compress.pyx
tests/unit/test_compression.py

Bug in the Cython code considered a return code of 0 to mean the decompression failed. 0 is a valid code when the size of the data is zero (i.e. emptry string).

Decompression fails with empty string

---

arctic/date/_mktz.py

My app use `ms_to_datetime` frequently, after profiling using [pyflame](https://github.com/uber/pyflame), I found the function takes `35.62%` of the total CPU time, and the bottleneck is in `mktz`(`31.87%`). I think it's better to cache results for the `mktz` function.

Cache for mktz

---

arctic/tickstore/tickstore.py

Since pandas 0.19.0, A warning will raise
> ***/arctic/tickstore/tickstore.py:547: FutureWarning: to_datetime is deprecated. Use self.to_pydatetime()
bucket, initial_image = TickStore._pandas_to_bucket(x[i:i + self._chunk_size], symbol, initial_image)
The `.py_datetime` [has been existed](https://github.com/pandas-dev/pandas/blob/v0.10.0/pandas/tslib.pyx#L261) (at least) since `v0.10.0` back to Dec 13, 2012.
- Changeset in pandas since 0.19.0: https://github.com/pandas-dev/pandas/commit/a9c15d356641e77553586154cccbdada50d7629d

Timestamp.to_datetime is deprecated in pandas

---

CHANGES.md
arctic/date/_mktz.py

Sharing tzfile objects doesn't appear to be safe particularly on DST
change:
https://github.com/dateutil/dateutil/issues/338

Revert "Cache for mktz #303"

---

.travis.yml

With most recent updates to the server test fixtures (pytest-server-fixtures) we
should be able to run with sudo: false again, thus enabling containers again. This
will result in a small but noticeable speedup in build times

Update travis.yml to use container build infrastructure again

---

arctic/date/_daterange.py

```python
DateRange(start=datetime.datetime(2016, 12, 25, 18, 23, 34, 15000, tzinfo=tzfile(u'/usr/share/zoneinfo/Asia/Shanghai')), end=datetime.datetime(2016, 12, 25, 20, 23, 34, 15000, tzinfo=tzfile(u'/usr/share/zoneinfo/Asia/Shanghai')))
```
looks good for `__repr__` but too ugly for `__str__`, especially in logs.
I think
```python
[2016-12-25 18:23:34.015000+08:00, 2016-12-25 20:23:34.015000+08:00)
```
should be much better.

Better format for DateRange.__str__

---

CHANGES.md
arctic/chunkstore/chunkstore.py
tests/integration/chunkstore/test_chunkstore.py

Enable audit logs on operations with the audit keyword arg. Writes supplied dict along with additional information into the audit collection

Support for audit logs in ChunkStore

---

arctic/chunkstore/date_chunker.py
tests/integration/chunkstore/test_chunkstore.py

fixes issue #324. Pandas doesnt do well with unsorted datetime indexes, so this ensures that they are sorted

Fix issue #324

---

CHANGES.md
arctic/tickstore/tickstore.py
tests/integration/tickstore/test_ts_read.py

By using the index bitfield masks we can return a sparse dataframe.
This is a behaviour change, as we don't return rows for timestamps where
the field wasn't updated.
Old code:
=========
```
%timeit l.read('3284.JP', date_range=adu.DateRange(20170101, 20170206))
1 loops, best of 3: 1.99 s per loop
%timeit l.read('3284.JP', date_range=adu.DateRange(20170101, 20170206),
columns=['DISC_BID1', 'BID'])
10 loops, best of 3: 82.2 ms per loop
%timeit l.read('3284.JP', date_range=adu.DateRange(20170101, 20170206),
columns=['DISC_BID1'])
10 loops, best of 3: 76.4 ms per loop
```
New code:
=========
```
%timeit l.read('3284.JP', date_range=adu.DateRange(20170101, 20170206))
1 loop, best of 3: 2.29 s per loop
%timeit l.read('3284.JP', date_range=adu.DateRange(20170101, 20170206), …
```

MDP-1754 Improve the memory and cpu performance of reading a subset of columns

---

setup.py
src/_compress.pyx

I fixed some compiling errors on Mac OS X. gcc-4.2 on Mac does not support OpenMP, so g++-6 has to be used.

Yjiangnan patch 1 for Mac OS X installation

---

arctic/store/_ndarray_store.py
arctic/store/_pandas_ndarray_store.py
arctic/store/version_store.py
tests/integration/store/test_ndarray_store_append.py
tests/integration/test_concurrent_append.py
tests/unit/store/test_ndarray_store.py

Make concurrent appends safe(r) by introduce a 'dirty_append' kwarg to the append() method. 
Any time an append may not be completely sequential with the previous version, it is flagged as 'dirty' and we make it multiprocess safe by concatenating and rewriting any previously appended chunks.

Make concurrent appends safe

---

arctic/store/_version_store_utils.py
arctic/store/version_store.py
tests/unit/store/test_version_store.py

We've got queries that take over 200 seconds, this makes them much
faster (milliseconds - 5 order of magnitude speedup, yay!).

$size queries can't use indexes, use alternative queries.

---

arctic/_compression.py

If we can't import the parallel/cython lz4, we should disable the PARALLEL flag.

If cython lz4 cannot import, disable parallel compression

---

.travis.yml
setup.py

When version 0.9.0 of lz4 was released, it broke arctic, so I pinned arctic to 0.8.2. This broke things internally so It was changed to <= 0.8.2. Now that lz4 latest works with arctic, we should move back to unpinning the version (as it originally was).

Revert lz4 pinning

---

.travis.yml
arctic/chunkstore/date_chunker.py
arctic/multi_index.py
arctic/scripts/arctic_copy_data.py
arctic/serialization/numpy_records.py
arctic/store/_pandas_ndarray_store.py
arctic/tickstore/tickstore.py
setup.py
tests/integration/chunkstore/test_chunkstore.py
tests/integration/store/test_pandas_store.py
tests/integration/tickstore/test_ts_read.py
tests/unit/test_multi_index.py
tests/unit/tickstore/test_toplevel.py

New versions of pandas have relocated tslib to _libs. This change supports previous versions and new versions of pandas.

Fix tslib issue with new version of pandas

---

arctic/_util.py
arctic/store/bson_store.py
tests/unit/store/test_bson_store.py

BSONStore instances generally don't have symbols (the idea is that they should be free-form), but we still want to be able to shard them when they get big enough. Ideally there would be a user-specified way to pick a key, _id is a good default at any rate.

Allow sharding on keys other than symbol, default BSONStore to shard on _id

---

arctic/store/bson_store.py
tests/unit/store/test_bson_store.py

The dreadful consequences of mindless copy-pasting. Mea culpa.

Remove replace_many, and fix replace_one

---

CHANGES.md
README.md
setup.py

Previously setup.py assumed you had a specific version of gcc installed. This corrects that and looks for the 3 most recent versions provided by homebrew, as well as issues a reasonable error if none of them exist. 
Also updates the README with information about macOS support

fix issue #372

---

arctic/chunkstore/chunkstore.py
arctic/chunkstore/date_chunker.py
tests/integration/chunkstore/test_chunkstore.py
tests/integration/chunkstore/test_fixes.py

Chunkstore was omitting the start and end times of chunks when converting the chunk sentinels to strings. This fixes that behavior and allows it to work with dates as well as datetimes.

Fix issue #384

---

CHANGES.md
arctic/arctic.py
tests/integration/test_arctic.py

Previously this did not work, you could only rename libraries named "test", a library named "test.test" was not renameable. 
see #343

Renaming libraries within a database/namespace

---

arctic/store/_ndarray_store.py
tests/integration/store/test_version_store.py

If we append to an empty array, we can end up with a situation where there are uncompressed chunks, but no compressed chunks. This causes _concat_and_rewrite to blow up when compressing the uncompressed data.

Handle case where appending to empty array fails in _concat_and_rewrite.

---

arctic/serialization/numpy_records.py
arctic/store/_ndarray_store.py

When looking at the memory usage deserialising large pandas dataframes then it became clear that the dataframes were taking more memory than they needed, roughly double.  
We have a df 2000 by 100000 with integer index and float64 data, this took around 2.6GB, but ask pandas how big it is and it reports 1.3GB. It came down to two copies of the data being held for each dataframe.  There was a bug to do with view vs copies of ndarrays that meant one copy of the entire ndarray (including the index) was being held by the multi-index and another copy of the data part of the array was being held by the dataframe.

Memory optimisation

---

arctic/tickstore/toplevel.py

These do not seem relevant in the general Arctic context.

Remove default columns in TopLevelTickStore

---

CHANGES.md
arctic/chunkstore/chunkstore.py
tests/integration/chunkstore/test_fixes.py

Fixes a bug where standalone segments were never cleaned up if enough appends lead to multiple segments for a chunk.

Fix issue #407

---

.travis.yml

Arctic has no python3 exclusive features, much less anything exclusive to 3.6 over 3.5. No reason have increased build times by running on two 3.X versions, especially now that 3.5 is bugfix only

remove python 3.5 from travis.yml

---

arctic/store/version_store.py

Logging message when deleting a symbol has severity WARN - this severity should be reserved for genuine potential issues rather than a regular operation.

Updating version_store.py to fix issue #423

---

arctic/chunkstore/date_chunker.py
tests/integration/chunkstore/test_fixes.py

date chunker in chunkstore does not currently respect open intervals from date range when filtering data frames by user supplied chunk_range

fix date chunker so it respects intervals

---

arctic/chunkstore/chunkstore.py
tests/integration/chunkstore/test_fixes.py

Dataframes without an index have no "index" field in their metadata,
so updating existing metadata does not remove the index field.
Also, metadata was incorrectly being stored. symbol, start, and end
are the index for the collection, but metadata was being
stored without an index (so it was defaulting to null,null,null)

Correctly set index in metadata and replace existing metadata

---

CHANGES.md
arctic/serialization/numpy_records.py
tests/integration/store/test_pandas_store.py

It's impossible to determine the dtype of a saved empty index from the saved information alone and pandas has the bad habit of defaulting to either float or int. We can work out whether a MultIndex level is meant to be a DatetimeIndex based on the presence of the separate timezone information. Based on this, we can cast back empty indices to DatetimeIndex where appropriate.
This is only a shim - a good fix would have us saving down all the dtypes for both indices and data. This should ensure that any arbitrary type empty series written out can be read back in as it was.
Fixes #440

Fix read of empty MultiIndex+tz Series

---

CHANGES.md
arctic/chunkstore/chunkstore.py
arctic/serialization/numpy_records.py
tests/integration/store/test_pandas_store.py

Using `iterator` can cause timeouts on the initial cursor that was used to query the dates for the symbol. This fixes that by resolving all the elements in the generator before creating the 2nd cursor.

Resolve issue 439 cursor timing out

---

arctic/chunkstore/chunkstore.py
tests/integration/chunkstore/test_fixes.py

previous changes fixed a bug where segments labels started with -1 and we not properly handled when the chunk size increased to more than 1 segment. This introduced a new bug where legacy data with -1 segments would not properly be removed and it would cause decompression errors during a read.
This fixes that by converting all -1 segments to 0 segments at library object instantiation.

fix legacy segments - issue-442

---

CHANGES.md
arctic/arctic.py

Since the quota has already been 'checked' we shouldn't letthe generation of informational statistics kill the write

Prevent exceptions in check_quota from killing a write

---

.gitignore
arctic/date/__init__.py
arctic/date/_util.py
arctic/tickstore/tickstore.py
tests/unit/date/test_util.py

The return value of `TickStore.max_date()` was a `datetime` of UTC timezone without `tzinfo`. It should be converted to local timezone. Please correct if this's a feature.

TickStore.max_date: convert to local timezone

---

tests/integration/scripts/test_enable_sharding.py

New version of pymongo has new default arg that mocks in the integration tests are not accounting for

Fix integration tests with pymongo 3.6

---

tests/integration/test_arctic.py

After Mongo 3.4 the index version is 2.
Mongo 3.4 can run with compatibility mode enabled and allow index version 1, but with 3.6 only version 2 is allowed.
https://docs.mongodb.com/manual/release-notes/3.4-compatibility/#compatibility-enabled
In our integration tests, we always expect version 1, which is now breaking.

Fix the failing integration test due to the Mongo upgrade to 3.6

---

arctic/serialization/numpy_records.py

The get_timezone library was moved around in 0.20 and 0.21. We are still using it even though it was deprecated, so adding some missing version compatibilities.
Related to #470

Re-adding compatibility for pandas 0.20.x

---

arctic/tickstore/tickstore.py
tests/integration/tickstore/test_ts_read.py

if the column is an object type, assume its a string. If its not an exception will be raised.

Support for strings in tickstore columns

---

CHANGES.md
arctic/store/version_store.py
tests/unit/store/test_version_store.py

We made unnecessarily multiple calls to _find_snapshots, while we could pre-compute and avoid pushing lots of mongo queries:
https://github.com/manahl/arctic/blob/master/arctic/store/version_store.py#L262
For collections with many symbols, many versions and many snapshots, the improvement is very significant with this fix:
```
Without optimisation:
Total time is: 80.6683588028
Count stats: mean=12.95, std=0.569, min=6, max=13
Time stats: mean=0.083851, std=0.042957, min=0.037374, max=0.484092
With Arctic fix:
Total time is: 11.6488740444
Count stats: mean=12.95, std=0.569, min=6, max=13
Time stats: mean=0.012107, std=0.003715, min=0.008276, max=0.067882
```

Fix slow list versions

---

CHANGES.md
arctic/store/version_store.py
tests/integration/store/test_version_store.py

VersionStore: _prune_previous_versions now retries the cleanup operation, preventing an exception to be raised during step downs.

Fix bug raised in issue #515

---

CHANGES.md
arctic/store/version_store.py
tests/integration/store/test_version_store.py
tests/unit/store/test_version_store.py

The commit 4015af8 fixes the first part of the problem: calls to find are now retried instead of raising OperationFailure. This is enough to solve all cases where a duplicated append happens, as mongo_retries are global to the append/write call.
However, the commit fd3c999 was added to make the code safer to potential issues that may cause an exception be raised after a version is created.

Fix for issue #517

---

README.md
setup.py

clang-6.0 includes openmp support by default, so the linker flag is no longer required so long as the compiler flag was included.  Therefore in [setup.py](https://github.com/manahl/arctic/blob/master/setup.py) make the default `link_args` empty at line 29, and if gcc is the installed compiler add the `link_arg` `-fopenmp` at line 50.  Also updated the ValueError to reference clang-6.0 (now default install when executing `brew install llvm`).
As I reviewed this before submission, I see that I could have deleted the comment at line 32 also as this is not true. _(fixed in subsequent commit)_

issue 521 - updated setup.py for clang-6.0

---

CHANGES.md
arctic/fixtures/arctic.py
arctic/store/_ndarray_store.py
tests/integration/store/test_ndarray_store.py
tests/integration/store/test_pandas_store.py

This line will https://github.com/manahl/arctic/blob/v1.63.0/arctic/store/_ndarray_store.py#L389 raise a `TypeError: invalid type promotion` if there is uncompressed data with a different dtype from the new data being written.
That line can be reached with a different dtype if the data is actually the same, except for a column name change. Moreover, uncompressed data can have a 'sha' value in versions prior to 1.41. So this is an issue mainly when migrating from old version.
This fixes issue https://github.com/manahl/arctic/issues/534

Check dtype before concatenating on write (issue #534)

---

arctic/serialization/numpy_arrays.py
arctic/store/bson_store.py
arctic/store/metadata_store.py
tests/integration/test_compress_integration.py
tests/unit/store/test_metadata_store.py
tests/unit/test_compress.py

Adding missing features:
- regex symbol lookup
- as_of support - show symbols valid starting with the provided date
- metadata field exact match queries

Add advanced query for list_symbols() similar to VersionStore

---

arctic/multi_index.py
arctic/tickstore/tickstore.py
setup.py
tests/integration/store/test_bitemporal_store.py
tests/integration/tickstore/test_ts_read.py
tests/integration/tickstore/test_ts_write.py
tests/unit/test_multi_index.py

latest version of pandas introduces some changes that affect how timezones are stored and used in `pandas.Timestamp`. This corrects the issues in the unit tests and in tickstore. See issue #566

Fix issues with pandas 0.23

---

arctic/store/_ndarray_store.py
tests/integration/store/test_ndarray_store_append.py

The latest numpy's astype will happily reorder your dtype column names without reordering the columns themselves. Previously we relied on astype to also reorder the columns.
We already have some code that effectively backports the old implementation so this just extends that.

Fix issue whereby appending can silently reorder columns

---

README.md
arctic/_util.py
arctic/arctic.py
arctic/chunkstore/chunkstore.py
arctic/fixtures/arctic.py
arctic/store/_ndarray_store.py
arctic/store/_version_store_utils.py
arctic/store/bson_store.py
arctic/store/version_store.py
tests/integration/chunkstore/test_chunkstore.py
tests/integration/scripts/test_arctic_fsck.py
tests/integration/store/test_ndarray_store.py
tests/integration/store/test_pickle_store.py
tests/integration/store/test_version_store.py
tests/integration/store/test_version_store_audit.py
tests/integration/store/test_version_store_corruption.py
tests/integration/test_arctic.py
tests/integration/test_compress_integration.py
tests/integration/tickstore/test_ts_read.py
tests/unit/store/test_bson_store.py
tests/unit/store/test_version_store.py
tests/unit/test_arctic.py
tests/unit/test_fixtures.py

Fixes issues #596 and #599
list_collection_names was added with pymongo 3.6.0:
https://github.com/mongodb/mongo-python-driver/blob/3.6.0/pymongo/database.py#L590
We switched to requiring pymongo>=3.6.0 recently:
https://github.com/manahl/arctic/blob/master/setup.py#L86
Therefore it is safe to simply replace collection_names with list_collection_names

fix failing integration tests on travis due to list_collection_names deprecation

---

CHANGES.md
README.md
docs/chunkstore.md
docs/versionstore.md
setup.py

Create initial first pass of version store documentation. I've tried to cover the most important use cases for the main methods of version store, focusing on the basic usecase (dataframes). Is surely not complete, but I think its much better than what we currently have (nothing) :)
I will squash the commits into a single commit

Version store documentation

---

tests/unit/date/test_util.py

Comparing datatime.datetime objects with timezones different from UTC can held different behaviours if we are at the boundaries of a daylight saving time change. E.g. This code 
```
d1 = dt(2007, 3, 25, 0, tzinfo=mktz('Europe/London'))
d2 = dt(2007, 3, 25, 1, tzinfo=mktz('Europe/London'))
print datetime_to_ms(d1) == datetime_to_ms(d2)
print d1 == d2
```
prints
```
True
False
```
For this reason, the test `test_datetime_to_ms_and_back()` fails depending on which timezone the machine is running from.
Reccomendation from [pytz](http://pytz.sourceforge.net/) are:
> The preferred way of dealing with times is to always work in UTC, converting to localtime only when generating output to be read by humans.

test datetimes: compare epoch instead of timestamps

---

arctic/date/_daterange.py
tests/unit/date/test_daterange.py

'DateRange.intersection' method returns CLOSED interval when intersecting ranges with same start[,end] and distinct interval values. 
It should return an  OPEN_*(>start) interval as it is subset of the same CLOSED_*(>=start)

Fixed small bug in DateRange.intersection

---

arctic/store/_ndarray_store.py
arctic/store/_pickle_store.py
arctic/store/_version_store_utils.py
tests/unit/store/test_ndarray_store.py
tests/unit/store/test_pickle_store.py

Mongo 3.6+ no longer uses the index to sort when using multi-key indexes ([SERVER-19402](https://jira.mongodb.org/browse/SERVER-19402)), therefore, we are now using the client to sort.
Using in-memory sorting in MongoDB 3.6+ risks hitting the 32MB memory limit, causing queries to fail.

Ensure Arctic performs well with MongoDB 3.6+

---

arctic/serialization/numpy_records.py
benchmarks/fast_serializable_check.py
tests/integration/chunkstore/test_chunkstore.py
tests/integration/chunkstore/test_utils.py
tests/integration/test_compress_integration.py
tests/unit/serialization/serialization_test_data.py
tests/unit/serialization/test_numpy_records.py
tests/unit/serialization/test_pandas_is_serializable.py

Issue #590
I extracted only the fast check improvement form the incremental serialization branch.
This has already been reviewed/approved:
https://github.com/dimosped/arctic/pull/1
It is turned off by default, and I'd like to include it in the next release

Complete implementation and tests for the fast is-serializable check

---

CHANGES.md
arctic/_util.py
arctic/exceptions.py
arctic/serialization/incremental.py
arctic/serialization/numpy_records.py
arctic/store/_pandas_ndarray_store.py
tests/integration/store/test_version_store.py
tests/unit/serialization/serialization_test_data.py
tests/unit/serialization/test_incremental.py

Issues: #648  and #577 
This is the compete PR for the implementation of the incremental serializer.
The aims/goals of incremental serialization are:
- to be the building block of the **internal** parallel/async redesign (there is an upcoming incremental PR)
- dramatically reduce the maximum memory footprint of write/append operations
- to improve speed for large dataframes
- to maintain binary compatibility with the existing numpy_records serializer
- to be configurable in terms of chunk sizes, offsets, and incremental checksumming
@yschimke  @bmoscon @jamesblackburn @pablojim  @willdealtry  feel free to add your comments and ask questions.
Many design choices are related to the idiosyncrasies of numpy/pandas typing and data representation, and might not be very straightforward, feel …

Incremental serialization complete implementation (not used, code complete)

---

arctic/_config.py
arctic/async/__init__.py
arctic/async/_workers_pool.py
arctic/async/async_arctic.py
arctic/async/async_utils.py
arctic/exceptions.py
benchmarks/async/async_benchmark.py
setup.py
tests/integration/test_async_arctic.py

Implements feature described in #668 .
This is compatible both with Python 2 and Python 3, without requiring third party libraries.
Currently uses multi-threading, not multi-processing.
The speed gains are roughly 2x for not too large data frames, and 1.5x for large:
```
Experiment results: async=False, chunks/write=2, writes/round=64, rounds=2, parallel_lz4=False, async_arctic_pool_workers=4: ['11.991', '0.000', '11.991', '11.991']
Experiment results: async=True, chunks/write=2, writes/round=64, rounds=2, parallel_lz4=False, async_arctic_pool_workers=2: ['7.028', '0.000', '7.028', '7.028']
Experiment results: async=True, chunks/write=2, writes/round=64, rounds=2, parallel_lz4=False, async_arctic_pool_workers=4: ['5.820', '0.000', '5.820', '5.820']
```
The API allows to get back a future, …

[EXPERIMENTAL] Initial implementation of the public arctic async api (Python 2 and 3)

---

docs/_config.yml

This reverts commit 44a202de7524d7152aa6f4d2bcb2dfe21807b9ad.
Github apparently commits this straight to master on trying out
githubpages, was not intentional.

Revert "Set theme jekyll-theme-cayman"

---

setup.py

Pinning pytest to <4.1 to fix this: 
https://github.com/manahl/arctic/issues/678
Not sure when pytest-cov will release next, this should unblock us for now.

Fix build by pinning pytest<4.1

---

.travis.yml
arctic/_compression.py
arctic/_config.py
arctic/arctic.py
arctic/chunkstore/chunkstore.py
arctic/date/_daterange.py
arctic/date/_util.py
arctic/fixtures/arctic.py
arctic/scripts/arctic_fsck.py
arctic/scripts/arctic_init_library.py
arctic/serialization/incremental.py
arctic/serialization/numpy_arrays.py
arctic/serialization/numpy_records.py
arctic/store/_ndarray_store.py
arctic/store/_pandas_ndarray_store.py
arctic/store/_pickle_store.py
arctic/store/_version_store_utils.py
arctic/store/audit.py
arctic/store/bson_store.py
arctic/store/metadata_store.py
arctic/store/version_store.py
arctic/tickstore/tickstore.py
setup.cfg
tests/integration/store/test_pandas_store.py
tests/unit/store/test_pandas_ndarray_store.py

This has multiple small changes made as was browsing the code. Fixes mostly fall into these categories:
* double quote in docstrings
* remove unnecessary brackets
* marking unused imports
* initializing dicts in one go
* Indents
* Variable renames
Also enabled pycodestyle with some disabled flags (eg. line length etc are disabled). The advantage being if any of the fixed issues now break, it will not allow that change. 
`pycodestyle --ignore=E122,E126,E223,E501,E731,W503,E722,W504 arctic`
should pass from now on.

Multiple small formatting changes and enabling pycodestyle in ci

---

setup.py

Internal builds might not have latest versions of pytest-cov and
the pinning might conflict there. The expectation is that whoever
upgrades pytest internally will upgraded pytest-cov as well.
In travis the latest versions of pytest-cov and pytest should be
fine.

Unpin pytest-cov

---

arctic/arctic.py

Adds basic logging to prevent the warning in: https://github.com/manahl/arctic/issues/27 similar to https://github.com/requests/requests/blob/master/requests/__init__.py#L124

Fix no handler in logging warning

---

arctic/multi_index.py
arctic/serialization/incremental.py
arctic/store/_ndarray_store.py
tests/integration/store/test_bitemporal_store.py
tests/unit/test_multi_index.py
tests/util.py

As it's removed from versions 0.24.0 and sort_index is supported
and recommended in previous versions

Pandas: use sort_index instead of sortlevel

---

arctic/store/_ndarray_store.py

This would help preventing issues where we are accessing this key
in versions without being initialized.
This is only done for cases where it's either HYBRID or ENABLED
mode as this field should not be used in other cases anyways.

Fixes #710: Initialize SEGMENT_SHA in versions for writes and appends

---

arctic/_cache.py
arctic/_config.py
arctic/arctic.py
tests/integration/test_arctic.py
tests/unit/test_arctic.py

list_libraries is a frequently called operation that can get
quite slow with a high amount of libraries. I noticed 4-5s+
for 7-8k libraries. Also the number of libraries is fairly
constant, so not much point in refetching the entire list every
time.
This adds a new collection in mongo which acts as a global cache
for all queries. The meta_db can be used for more accounting and
metadata storage in future, and this collection can be used for
caching other stuff as well.
It's best effort as if you don't have permissions or the data
does not exist in the cache it will just use the list_libraries.
The idea is to not require admin for reads and not expect the user
to have write access to a collection on writes.

Fix #587 Add a best effort cache option for list_libraries

---

arctic/_cache.py
arctic/arctic.py
tests/integration/test_arctic.py

Fixes 2 things:
a) Initialize library will now add to cache even if the cache is empty by upserting. This is required as an user might be caught out when trying out arctic by just adding a lib and doing list_libraries. If sufficient permissions do not exist, it will silently skip this operation.
b) If reload_cache was the first op after initializing arctic, the connection might not yet be created. This ensures it.

Upsert append

---

setup.py

pypandoc deprecated the old function and does not render correctly with RST anymore (unless you specify the markdown flavor)
see https://pypi.org/project/arctic/
the project description is all broken. It will look much better once this is merged and another release is done

Fix conversion error

---

arctic/store/_pickle_store.py

We have an issue where datetimes / numpy arrays etc written in py2
can't be read back now. This tries to use 'bytes' as encoding and
if that does not work, it tries to use latin. This method is given
in the official docs:
https://docs.python.org/3/library/pickle.html#pickle.load

Fix issue with pickled numpy arrays in py2 read back in py3

---

arctic/serialization/numpy_records.py
arctic/store/_pandas_ndarray_store.py
tests/integration/store/test_pandas_store.py

This adds a config flag which allows users to convert the py2 str
type columns (which are bytes) to be unicode when read back. This
is useful for arctic users migrating from python2 to python3 and
expecting back a py3 string type type which is unicode.

Add a way to force bytes columns to unicode via a config flag

---

arctic/store/_pickle_store.py

This causes an issue with unicode strings in py2. Instead I am using
something similar to:
https://github.com/pandas-dev/pandas/blob/master/pandas/io/pickle.py#L157
where the default is the better option rather than forcing it to use
bytes.

Do not use bytes when loading back pickled objects

---

arctic/_cache.py
arctic/_config.py
arctic/arctic.py
tests/integration/test_arctic.py
tests/unit/test_arctic.py

This allows us to enable and disable the cache on the fly for list_libraries.
Also allows us to change the expiry period for returning the results.
If user does not have write permissions to meta_db, it will use the slow path. To fix this, you can give permissions using:
db.getSiblingDB('admin').grantRolesToUser("research", [{role: "readWrite", db: "meta_db"}])

Add global settings for caching list_libraries

---

arctic/serialization/numpy_records.py

Currently it will break for empty columns due to the missing check.

Fix #777: Handle zero columns when converting to unicode

---

setup.py

Don't think we need to convert it ourselves with this option as given here; https://packaging.python.org/guides/making-a-pypi-friendly-readme/

Just specify markdown in setup.py instead of manually converting

---

arctic/serialization/numpy_arrays.py

Not sure why, but for some reason this log line was an info. Hit an error that triggered this path and it was extremely hard to track down the issue until I changed this line to a warning (it gives the column name, which is critical).

Update info log message in exception handler in chunkstore

---

tests/integration/chunkstore/test_chunkstore.py
tests/integration/test_arctic.py
tests/integration/test_compress_integration.py
tests/integration/tickstore/test_toplevel.py
tests/integration/tickstore/test_ts_read.py
tests/unit/chunkstore/test_date_chunker.py
tests/unit/serialization/test_numpy_arrays.py
tests/unit/store/test_pickle_store.py
tests/unit/store/test_version_store.py
tests/unit/test_arctic.py
tests/unit/test_decorators_unit.py
tests/unit/tickstore/test_toplevel.py

This breaks our tests as we use str(e) everywhere and as the above
PR changes the behaviour of str to be the same as repr which is to
print the ExceptionInfo Object, which breaks our tests as we expect str(e) to contain the message

Fix tests broken due to https://github.com/pytest-dev/pytest/issues/5412

---

arctic/_config.py
arctic/store/_pickle_store.py

Currently we try to bson encode if the data is less than a given size and store it in
the version collection, but pickling might be preferable if we have characters that don't
play well with the bson encoder or if you always want your data in the data collection.

Add a config option to skip bson encoding in pickle store

---

arctic/_config.py

Explicitly disabling forward pointers and can't be set from env accidentally as it might cause data corruption. Once I finish the revert PR, will completely remove this.

Hardcode fwd pointer disabling

---

arctic/decorators.py

These can contain index and key errors that must be raised immediately. 
If we retry, then the error that is raised is often different to the one that caused the original problem - for example duplicate key error for entries that have just been added.

Don't retry BulkWriteErrors

---

arctic/serialization/numpy_arrays.py
tests/unit/serialization/test_numpy_arrays.py

Bug in numpy serializer objify function causes issues in dataframe construction when a given column passed into the columns does not exist. 
```
import numpy as np
import pandas as pd
from arctic.serialization.numpy_arrays import FrameConverter, FrametoArraySerializer
f = FrameConverter()
df = pd.DataFrame(data={'one': ['a', 'b', 'c', np.NaN]})
res = f.objify(f.docify(df), columns=['one', 'two'])
```
```
Traceback (most recent call last):
File "/home/abai/pyenvs/arctic/lib/python3.6/site-packages/ipython-7.7.0-py3.6.egg/IPython/core/interactiveshell.py", line 3326, in run_code
exec(code_obj, self.user_global_ns, self.user_ns)
File "<ipython-input-4-9e264fac0a78>", line 1, in <module>
res = f.objify(f.docify(df), columns=['one', 'two'])
File …
```

Fix missing column handling in numpy serializer.

---

arctic/store/_version_store_utils.py

There is a small typo in arctic/store/_version_store_utils.py.
Should read `verifies` rather than `verififes`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: fix simple typo, verififes -> verifies

---

arctic/_util.py
arctic/store/_pandas_ndarray_store.py
tests/integration/store/test_pandas_store.py
tests/unit/store/test_pandas_ndarray_store.py

I produced a fix for the import errors/deprecations in issue #815.
With a recent version of Pandas, importing Panel results in an error, not just a future warning.
Please have a look at it.

Fix for issue #815

---

setup.py
tests/unit/store/test_version_store_audit.py

Checking which version of pandas starts becoming problematic

Fix #893 : Pin Pandas and numpy versions to get build working

---

arctic/_cache.py
arctic/arctic.py
arctic/store/_pickle_store.py

If _cache is not initialized - I have seen this in some contexts with forking involved - just return the uncached list_libraries.
Travis seems to be completely busted, checking if it's working for new  PR's, hence closing and reopening one

Handle uninitialized cache object

---

arctic/chunkstore/chunkstore.py

Correcting the index to correctly be used in read(..)
https://www.mongodb.com/blog/post/performance-best-practices-indexing
See ESR rule

Speed up chunkstore reads with index

---

arctic/serialization/numpy_arrays.py

**Summary**
Speedup FrametoArray serializer for ChunkStore by removing intermediate DataFrame construction.
The majority of the time spent for serialization is spent on the following:
1. Constructing intermediate DataFrames
2. Setting the index:
By removing the intermediate DataFrame construction (so we only use numpy arrays and construct the DataFrame at the very end) and constructing the index separately, we can speed the serialization up significantly. 
**Performance comparisons**
---------------------------------
**No Index - Series**
```
df = pd.Series(range(100))
a = FrametoArraySerializer().serialize(df)
```
1. Single Chunk:
2. Multiple Chunks (data in list):
**With Index - Series**
```
df = pd.Series(range(100), index=pd.Index(range(100), name='A'))
a = …
```

Speedup FrametoArray serializer for ChunkStore

---

arctic/serialization/numpy_arrays.py
tests/unit/serialization/test_numpy_arrays.py

The following change https://github.com/man-group/arctic/pull/909 introduced a bug with column subsetting. 
**Changes**
* Added tests for column subsetting
**Bugfixes**
* Fixed column subsetting issue 
* Fixed pre-existing error where objify would error out if dataFrame had no index and column requested did not exist in a given chunk.

Bugfix:  Fix column subsetting bug in numpy deserializer

---

.circleci/config.yml
CHANGES.md
README.md
arctic/_util.py
arctic/arctic.py
setup.py
tests/integration/chunkstore/test_chunkstore.py
tests/integration/chunkstore/test_fixes.py
tests/integration/chunkstore/test_utils.py
tests/integration/chunkstore/tools/test_tools.py
tests/integration/store/test_pandas_store.py
tests/integration/store/test_version_store.py
tests/integration/tickstore/test_ts_write.py
tests/unit/serialization/test_numpy_arrays.py
tests/unit/test_util.py
tests/util.py

I rebased this branch to pull in the fixed tests.  The actual issue this PR fixes in  arctic._util.mongo_count() in _util.py which used to run very slowly with filter == {}, and pymongo 3.11.0.

Pymongo 3.11.0 avoid slow mongo_count

---

arctic/serialization/numpy_arrays.py
tests/unit/serialization/test_numpy_arrays.py

Reverting the following commits:
- ddb31d0
- 8118025
2 bugs need to be addressed before this change can go in:
- missing data in string columns need to be converted to NaNs
- In the case of multiple chunks being passed into the Serializer, if a column is present in one chunk and not another AND the missing column is of datetime type, it needs to fill with NaT's.

Revert serialization optimization

---

.circleci/config.yml
CHANGES.md
README.md
arctic/serialization/numpy_arrays.py
setup.py

Bugfix: #932 revert serialization-optimization (#909, #910) (chunkStore fixes removed that broke 1.80.1)
pinned tomli==1.2.3; python_version=='3.6'

release/1.80.2 

---

arctic/store/_ndarray_store.py
tests/integration/store/test_ndarray_store.py

For large ndarrays, rows_size comes out to be greater than CHUNKS_SIZE, thus the value becomes 0. To handle division by zero, add 1 to rows_per_chunk which will not make a difference in the general case

Handle zero rows_per_chunk for ndarray_store

---

CHANGES.md
arctic/serialization/numpy_records.py
tests/unit/serialization/test_numpy_records.py

Due to an earlier change in this area, a regression was introduced where `dateutil.timezone.tzutc()` was serialized as the string `"tzutc()"`. `pandas` is unable to create a timezone from this, so data could not be reconstructed.
This change restores the old behaviour where `dateutil.timezone.tzutc()` is serialized as the string `"UTC"`.
Another prior fix to consistently serialize `dateutil.timezone.gettz("UTC")` for multi-level indexes is also extended in this change to cover single level indexes.

fix: Handle index timezones of dateutil.timezone.tzutc()

---

.readthedocs.yaml
docs/index.md
docs/requirements.txt
mkdocs.yml

- Some of the links were not working from GitHub markdown docs, some needed to be updated.
- Removed requirements.txt module versions as these were causing docs build to fail. After changing these the docs build was successful locally.

Updated links to ArcticDB website and docs

---

arctic/tickstore/tickstore.py

Speedup of Tickstore read datetime index conversion by ~40x.
Overall runtime improvement is around 3-4x on average, but this can vary depending on the mongo latency. 
```
%timeit  pd.DatetimeIndex(np.concatenate(rtn[INDEX]).astype('datetime64[ms]'), tz='UTC')
1.76 s ± 59.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
%timeit pd.to_datetime(np.concatenate(rtn[INDEX]), utc=True, unit='ms')
1min 16s ± 1.74 s per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
**In the current implementation, the datetime conversion takes ~60% of the total runtime:**
**The new implementation drops it down to ~5%**
**Output of both implementations is identical (tested on 22.5 million values).**

Speedup tickstore read date index conversion
